---
- name: Install and configure Kea DHCP server
  hosts: localhost
  become: true
  tasks:
    - name: Install Kea DHCP server and additional packages
      apt:
        name:
          - curl
          - apt-transport-https
          - kea-dhcp4-server
        state: present

    - name: Create Kea configuration directory
      file:
        path: /etc/kea
        state: directory
        mode: '0755'

    - name: Ensure kea-api-password file exists with a random password
      copy:
        dest: /etc/kea/kea-api-password
        content: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
        owner: root
        group: _kea
        mode: '0640'

    - name: Configure Kea DHCP server
      copy:
        dest: /etc/kea/kea-dhcp4.conf
        content: |
          {
            "Dhcp4": {
              "interfaces-config": {
                "interfaces": [ "eth0" ]
              },
              "control-socket": {
                "socket-type": "unix",
                "socket-name": "/run/kea/kea4-ctrl-socket"
              },
              "lease-database": {
                "type": "memfile",
                "lfc-interval": 3600
              },
              "valid-lifetime": 600,
              "max-valid-lifetime": 7200,
              "subnet4": [
                {
                  "id": 1,
                  "subnet": "10.0.0.0/24",
                  "pools": [
                    {
                      "pool": "10.0.0.2 - 10.0.0.10"
                    }
                  ],
                  "option-data": [
                    {
                      "name": "routers",
                      "data": "10.0.0.1"
                    },
                    {
                      "name": "domain-name-servers",
                      "data": "1.1.1.1, 8.8.8.8"
                    },
                    {
                      "name": "domain-name",
                      "data": "domain.console"
                    }
                  ],
                  "reservations": [
                    {% for host in hosts_1972 %}
                    {
                      "hw-address": "{{ host.mac.eth0 }}",
                      "ip-address": "{{ host.ip.eth0 }}"
                    }{% if not loop.last %},{% endif %}
                    {% endfor %}
                  ]
                }
              ]
            }
          }
        mode: '0644'

    - name: Reload Kea DHCP server configuration
      command: >
        kea-shell --host 127.0.0.1 --port 8000 --auth-user kea-api
        --auth-password $(cat /etc/kea/kea-api-password)
        --service dhcp4 config-reload