---
- name: Install and configure MetalLB in L2 mode
  hosts: all
  become: true
  tasks:
    - name: Allow TCP traffic on port 7946
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 7946
        jump: ACCEPT

    - name: Allow UDP traffic on port 7946
      ansible.builtin.iptables:
        chain: INPUT
        protocol: udp
        destination_port: 7946
        jump: ACCEPT

    - name: Allow TCP traffic on port 7946 for outgoing traffic
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: 7946
        jump: ACCEPT

    - name: Allow UDP traffic on port 7946 for outgoing traffic
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 7946
        jump: ACCEPT


- name: Install and configure MetalLB in L2 mode
  hosts: master
  tasks:
    - name: Download MetalLB manifest
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml"
        dest: "/tmp/metallb.yaml"

    - name: Apply MetalLB manifest
      ansible.builtin.command:
        cmd: "kubectl apply -f /tmp/metallb.yaml"
      changed_when: false

    - name: Ensure MetalLB namespace is ready
      ansible.builtin.command:
        cmd: "kubectl wait --namespace metallb-system --for=condition=available --timeout=60s deploy/controller"
      changed_when: false

    - name: Create MetalLB config file
      ansible.builtin.copy:
        dest: "/tmp/metallb-config.yaml"
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: 1972-ip-pool
            namespace: metallb-system
          spec:
            addresses:
            - {{kubernetes_metallb_pool}}
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-adv
            namespace: metallb-system

    - name: Apply MetalLB config
      ansible.builtin.command:
        cmd: "kubectl apply -f /tmp/metallb-config.yaml"
      changed_when: false

    - name: Verify MetalLB deployment
      ansible.builtin.command:
        cmd: "kubectl get pods -n metallb-system"
      register: metallb_status
      changed_when: false

    - name: Show MetalLB status
      ansible.builtin.debug:
        msg: "{{ metallb_status.stdout }}"
