- name: Create Kubernetes namespaces for eightbitsaxlounge
  hosts: master
  tasks:
    - name: Create namespaces for dev, test, and prod
      command: kubectl create namespace {{ item }}
      args:
        warn: false  # Suppresses warnings if the namespace already exists
      loop:
        - eightbitsaxlounge-dev
        - eightbitsaxlounge-test
        - eightbitsaxlounge-prod
      register: namespace_creation

    - name: Debug namespace creation output
      debug:
        var: namespace_creation.results