---
- name: Install and configure Kea DHCP server
  hosts: localhost
  become: true
  tasks:
    - name: Install ansiblehosts.j2 template
      template:
        src: ansiblehosts.j2
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: '0644'