---
- name: Deploy Flannel on Kubernetes
  hosts: master
  vars:
    ansible_user: mchellmer
  tasks:
    - name: Apply kube-flannel
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml {{ kubectl_args | default('') }}