---
- name: Deploy K3s with Ingress
  hosts: master, worker
  become: true
  vars:
    ansible_user: mchellmer

  tasks:
    - name: Install K3s on master
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server --cluster-init
      when: "'master' in group_names"

    - name: Get K3s token from master to join
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true

    - name: Install K3s on worker
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ groups['master'][0] }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token']['stdout'] }} sh -
      when: "'worker' in group_names"

    - name: Save K3s token
      set_fact:
        k3s_token: "{{ k3s_token.stdout }}"
      delegate_to: localhost
      run_once: true

    - name: Create .kube directory
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory

    - name: Copy K3s kubeconfig to user's kube config
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
        remote_src: yes
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true