apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: eightbitsaxlounge
    component: db
spec:
  selector:
    app: eightbitsaxlounge
    component: db
  ports:
  - port: 5984
    targetPort: 5984