name: CouchDB Release

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build-and-push:
    name: Build and Push CouchDB Image
    runs-on: self-hosted  # Use your Raspberry Pi self-hosted runner
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/couchdb:latest ./db
        docker push ghcr.io/${{ github.repository_owner }}/couchdb:latest

  deploy:
    name: Deploy CouchDB to Kubernetes
    needs: build-and-push
    runs-on: self-hosted  # Use your Raspberry Pi self-hosted runner
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubernetes Config
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Deploy CouchDB Resources
      run: |
        kubectl apply -f ./db/k8s/deployment.yaml
        kubectl apply -f ./db/k8s/service.yaml